
### 5. Stretch Goals

**a. Add Monitoring/Metrics**

You can integrate Prometheus and Grafana for monitoring. Here is a basic setup for Prometheus:

**Prometheus Deployment**

```yaml
# prometheus-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
